server:
  port: 8110
  
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
    properties.hibernate.hbm2ddl.auto : create
    
  h2:
    console:
      enabled: true
      path: /h2
