server:
  port: 8110
  
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/miniautorizador}
    username: root
    password:

